baseURL = "https://leosoamen.github.io/"
languageCode = "fr-ca"
defaultContentLanguage = "fr"
author = "Leonardo Mendonca"
title = "Leonardo's Blog"
theme = "vitae"
paginate = 5
enableRobotsTXT = true

publishdir = "../docs"

[params]
    homepage = false
    avatar = "/images/self.jpg"